name: Testes PR

on:
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test -x integrationTest

      - name: Run unit tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew integrationTest

      - name: Generate Coverage Report
        run: mvn jacoco:report

      - name: Check Coverage
        run: |
          COVERAGE=$(mvn jacoco:report | grep -A 1 '<counter type="INSTRUCTION" missed="0" covered="' | grep 'covered' | sed -n 's/.*covered="\([0-9]*\)".*/\1/p')
          THRESHOLD=80
          if [ "$COVERAGE" -lt "$THRESHOLD" ]; then
            echo "Coverage is below threshold"
            exit 1
          fi
